name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-format:
    name: Lint and Format Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Check formatting
        run: make format-check

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build binary
        run: make build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: make test

